### ISSUE TITLE
White space in the bottom

### ISSUE THREAD

**Issue by josealvarezn** [hanford/Instachrome#1]
Hi, @hanford!

I love this extension, but I have a little problem with a weird white space in the bottom of the frame. Check the attachment. 

Thanks!

![screen shot 2017-05-12 at 2 16 05 pm](https://cloud.githubusercontent.com/assets/16816916/26011140/d33afe74-371d-11e7-884a-ae77d07410f4.png)

**Comment by hanford** [comment]
Thanks for the feedback @josealvarezn, I noticed that this morning and I believe I fixed it with this commit: https://github.com/hanford/Instachrome/commit/e4780628942b4ff7f24e3083f48db8950f10dfd1

Can you remove the extension and reinstall and let me know if it’s still happening? Seems to be fixed on my end.

Here is what I'm seeing - http://d.pr/v/y4Yhs

**Comment by josealvarezn** [comment]
Now works. Thanks, Jack! 👌
