### ISSUE TITLE
Pop-up wrong position at upload picture on Mac!

### ISSUE THREAD

**Issue by josealvarezn** [hanford/Instachrome#2]
Hi, again Jack!
I have another little problem with the position of the Mac file pop-up when the icon it's on the right position of Chrome, the file pop-up crops the select action button.

![image](https://cloud.githubusercontent.com/assets/16816916/26011524/746c0968-371f-11e7-8ad2-3d43afa117e7.png)

**Comment by josealvarezn** [comment]
When I move the icon to the left position works fine.

![image](https://cloud.githubusercontent.com/assets/16816916/26011666/08467bf0-3720-11e7-9ffa-fe3af03a11d3.png)

**Comment by hanford** [comment]
Yikes! unfortunately this isn't something I can change 😕 because it's how the operating system handles `input[type=file]`

**Comment by josealvarezn** [comment]
Ok, I understand! Thanks!
