### ISSUE TITLE
Idea: option to pin the window of Instachrome

### ISSUE THREAD

**Issue by josealvarezn** [hanford/Instachrome#3]
Hi, @hanford!

What do you think, about the idea to pin the window of Instachrome on Chrome?

**Comment by hanford** [comment]
Not a bad idea, I'm also thinking about allowing the user to customize the dimensions of the popuo

**Comment by josealvarezn** [comment]
Nice! It's a good idea, too! 👏

**Comment by hanford** [comment]
@josealvarezn I rewrote how the layout logic works that'll ship once this lands https://github.com/segmentio/chrome-sidebar/pull/1

Here is a [preview](http://d.pr/v/ZN3ci) 🎉

**Comment by josealvarezn** [comment]
I liked it! 😱

**Comment by hanford** [comment]
Should be live
