### ISSUE TITLE
Please add back/forward buttons

### ISSUE THREAD

**Issue by yefim** [hanford/Instachrome#4]
Sometimes I visit a profile and then there's no way to go back to where I was scrolling the feed 😱

**Comment by hanford** [comment]
Good idea @yefim, currently that's sort of a non trivial addition considering the way things work - I'll keep this issue open for a rainy day though!

**Comment by yefim** [comment]
@hanford I think you can achieve this by running `window.history.back()` inside of the instagram frame. Maybe bind some events via `window.postMessage`?
